### PR TITLE
Add Builtin quit and exit

### LINKED ISSUE #387: ENABLE_USER_SITE not defined in site.py
For bundled applications that include `jupyter-core>=4.9`, the following error is generated:
```python
AttributeError: module 'site' has no attribute 'ENABLE_USER_SITE'
```

For example, see https://github.com/spyder-ide/spyder/issues/16649#issuecomment-954136171

### PR DESCRIPTION
**Pull request by mrclary**
Fixes #387.

* Added builtin definitions for 'quit' and 'exit'
* Set `ENABLE_USER_SITE=False`

### CODE REVIEW

**Comment by MAKOMO** [comment]
Shouldn't that temporary fix for #380 also be applied to the PyQt6 version?

**Comment by mrclary** [comment]
@MAKOMO I haven't worked with Qt6 yet, but if you think it should be applied feel free to add another commit to this PR.

**Comment by mrclary** [comment]
@ronaldoussoren, since you added `ENABLE_USER_SITE` in 5150910, I changed this PR to only include the addition of `quit` and `exit` to the `builtins`. I also removed the temporary fix for Qt5.

**Comment by ronaldoussoren** [comment]
PR looks OK. Thanks!

**Pull request merged**
