### PR TITLE
Port examples to wxpython 40

### PR DESCRIPTION
**Pull request by hamishmb**
This creates a new subfolder under the examples/wxPython folder for wxPython 4.0.

In this are the same examples from examples/wxPython/2.5, but with fixes for Python 3 and wxPython 4.0. I successfully managed to get the doodle examples working (and fix deprecation warnings), but not the others as I can't figure out what's wrong with the wxglade example, and files seem to be missing for the drpython example. The doodle examples have been tested to packages successful with py2app and to work with wxPython 4.1.

This pull request is part of the issue I raised at https://github.com/ronaldoussoren/py2app/issues/321#issuecomment-743160565 relating to packaging wxPython 4.1.x with py2app, seeing as I needed a minimal sample.

I appreciate that you might not want this pull request, especially seeing as I couldn't fix everything, but thought I might as well submit anyway as it does add a little bit of value at least.

### CODE REVIEW

**Comment by ronaldoussoren** [comment]
Could you drop the wxglade and drpython examples from your PR? 

The important bit is having an example that uses a recent version of wxPython (and Python 3).

**Comment by ronaldoussoren** [comment]
"working" as in, the script works without using py2app. I can look into any issues on the py2app side.

**Comment by hamishmb** [comment]
Okay, done. The example works with py2app just fine with wxPython 4.0.x as long as the fixes at https://github.com/ronaldoussoren/py2app/issues/252 are used, and with wxPython 4.1.x as long as those fixes are used and argv emulation is disabled.

**Comment by hamishmb** [comment]
Thanks!

**Pull request merged**
